<?php

namespace App\Services\AI;

final class KeywordRules
{
    public const RULES = [
        'ifood' => 'Alimentação', 'uber eats' => 'Alimentação', 'rappi' => 'Alimentação',
        'aiqfome' => 'Alimentação', 'james delivery' => 'Alimentação', 'ze delivery' => 'Alimentação',
        'mcdonalds' => 'Alimentação', 'burger king' => 'Alimentação', 'subway' => 'Alimentação',
        'pizza hut' => 'Alimentação', 'outback' => 'Alimentação', 'starbucks' => 'Alimentação',
        'cafeteria' => 'Alimentação', 'padaria' => 'Alimentação', 'restaurante' => 'Alimentação',
        'lanchonete' => 'Alimentação', 'mercado' => 'Alimentação', 'supermercado' => 'Alimentação',
        'carrefour' => 'Alimentação', 'extra' => 'Alimentação', 'pao de acucar' => 'Alimentação',
        'assai' => 'Alimentação', 'atacadao' => 'Alimentação', 'tenda atacado' => 'Alimentação',
        'dia' => 'Alimentação', 'hortifruti' => 'Alimentação', 'acougue' => 'Alimentação',
        'sushi' => 'Alimentação', 'churrascaria' => 'Alimentação', 'habibs' => 'Alimentação',
        'giraffas' => 'Alimentação', 'kfc' => 'Alimentação',
        'uber' => 'Transporte', '99app' => 'Transporte', '99 corrida' => 'Transporte',
        '99 app' => 'Transporte', 'cabify' => 'Transporte', 'in driver' => 'Transporte',
        'shell' => 'Transporte', 'ipiranga' => 'Transporte', 'br mania' => 'Transporte',
        'ale' => 'Transporte', 'posto' => 'Transporte', 'combustivel' => 'Transporte',
        'gasolina' => 'Transporte', 'estapar' => 'Transporte', 'zona azul' => 'Transporte',
        'estacionamento' => 'Transporte', 'pedagio' => 'Transporte', 'sem parar' => 'Transporte',
        'conectcar' => 'Transporte', 'tarifa azul' => 'Transporte', 'metro' => 'Transporte',
        'cptm' => 'Transporte', 'onibus' => 'Transporte', 'bilhete unico' => 'Transporte',
        'buser' => 'Transporte',
        'aluguel' => 'Moradia', 'condominio' => 'Moradia', 'iptu' => 'Moradia',
        'energia' => 'Moradia', 'enel' => 'Moradia', 'cpfl' => 'Moradia',
        'light' => 'Moradia', 'cemig' => 'Moradia', 'eletropaulo' => 'Moradia',
        'agua' => 'Moradia', 'sabesp' => 'Moradia', 'comgas' => 'Moradia',
        'gas' => 'Moradia', 'internet' => 'Moradia', 'vivo' => 'Moradia',
        'claro' => 'Moradia', 'tim' => 'Moradia', 'oi' => 'Moradia',
        'drogaria' => 'Saúde', 'drogasil' => 'Saúde', 'pacheco' => 'Saúde',
        'pague menos' => 'Saúde', 'drogaria sao paulo' => 'Saúde', 'farmacia' => 'Saúde',
        'hospital' => 'Saúde', 'clinica' => 'Saúde', 'consulta' => 'Saúde',
        'exame' => 'Saúde', 'laboratorio' => 'Saúde', 'unimed' => 'Saúde',
        'amil' => 'Saúde', 'sulamerica' => 'Saúde', 'bradesco saude' => 'Saúde',
        'hapvida' => 'Saúde', 'notredame' => 'Saúde', 'odonto' => 'Saúde', 'dentista' => 'Saúde',
        'netflix' => 'Lazer', 'spotify' => 'Lazer', 'amazon prime' => 'Lazer',
        'prime video' => 'Lazer', 'disney' => 'Lazer', 'disney plus' => 'Lazer',
        'hbo' => 'Lazer', 'hbo max' => 'Lazer', 'max' => 'Lazer', 'paramount' => 'Lazer',
        'apple tv' => 'Lazer', 'apple music' => 'Lazer', 'youtube' => 'Lazer',
        'youtube premium' => 'Lazer', 'deezer' => 'Lazer', 'twitch' => 'Lazer',
        'steam' => 'Lazer', 'playstation' => 'Lazer', 'xbox' => 'Lazer',
        'nintendo' => 'Lazer', 'epic games' => 'Lazer', 'cinemark' => 'Lazer',
        'kinoplex' => 'Lazer', 'ingresso' => 'Lazer', 'eventim' => 'Lazer',
        'sympla' => 'Lazer', 'bar' => 'Lazer', 'balada' => 'Lazer', 'show' => 'Lazer',
        'amazon' => 'Compras', 'mercado livre' => 'Compras', 'magalu' => 'Compras',
        'magazine luiza' => 'Compras', 'americanas' => 'Compras', 'casas bahia' => 'Compras',
        'shein' => 'Compras', 'shopee' => 'Compras', 'ali express' => 'Compras',
        'renner' => 'Compras', 'c&a' => 'Compras', 'riachuelo' => 'Compras',
        'marisa' => 'Compras', 'zara' => 'Compras', 'leroy merlin' => 'Compras',
        'leroy' => 'Compras', 'tok stok' => 'Compras', 'havan' => 'Compras',
        'udemy' => 'Educação', 'coursera' => 'Educação', 'alura' => 'Educação',
        'rocketseat' => 'Educação', 'origamid' => 'Educação', 'duolingo' => 'Educação',
        'babbel' => 'Educação', 'busuu' => 'Educação', 'escola' => 'Educação',
        'colegio' => 'Educação', 'faculdade' => 'Educação', 'universidade' => 'Educação',
        'fiap' => 'Educação', 'insper' => 'Educação', 'fgv' => 'Educação',
        'livraria' => 'Educação', 'livro' => 'Educação', 'saraiva' => 'Educação',
        'cultura' => 'Educação',
        'banco' => 'Serviços', 'itau' => 'Serviços', 'bradesco' => 'Serviços',
        'nubank' => 'Serviços', 'santander' => 'Serviços', 'caixa' => 'Serviços',
        'banco do brasil' => 'Serviços', 'inter' => 'Serviços', 'banco pan' => 'Serviços',
        'c6 bank' => 'Serviços', 'origem' => 'Serviços', 'will bank' => 'Serviços',
        'picpay' => 'Serviços', 'mercado pago' => 'Serviços', 'pagseguro' => 'Serviços',
        'stone' => 'Serviços', 'cielo' => 'Serviços', 'rede' => 'Serviços',
        'tarifa bancaria' => 'Serviços', 'anuidade' => 'Serviços', 'taxa' => 'Serviços',
        'iof' => 'Serviços', 'imposto' => 'Serviços', 'darf' => 'Serviços',
        'inss' => 'Serviços', 'detran' => 'Serviços', 'cartorio' => 'Serviços',
        'correios' => 'Serviços', 'sedex' => 'Serviços',
        'salario' => 'Salário', 'folha' => 'Salário', 'pagamento mensal' => 'Salário',
        'pix recebido' => 'Outros (receita)', 'transferencia recebida' => 'Outros (receita)',
        'freelance' => 'Freelance', 'reembolso' => 'Reembolso', 'cashback' => 'Outros (receita)',
        'rendimento' => 'Investimentos', 'dividendo' => 'Investimentos', 'renda fixa' => 'Investimentos',
    ];

    public static function all(): array
    {
        return self::RULES;
    }
}
